In [1]:
import pandas as pd

In [15]:
rel2 = pd.read_csv("진짜 정돈된 것.csv")

df2 = pd.DataFrame(rel2)
df2

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
0,"피지컬 AI, 온디바이스 AI","드론, 로봇",25-Dec,통신/전자,"피지컬 AI, 온디바이스 AI",차세대,Reaper/Predator Unmanned Aerial Vehicles (UAVs),09-Mar,same,16.8,high,"미국은 무인기 기술의 글로벌 리더이며, Reaper/Predator UAV는 200..."
1,Dagaie NG,함정,25-Nov,해상/해군,대함 미사일 기만체계,최신,AN/ALE-47 Countermeasures Dispensing System,Sep-88,same,37.2,high,AN/ALE-47 대응수단 분배 시스템은 1988년부터 미군에 의해 사용되어 왔으며...
2,후방지역 사단급이하 전술통신체계,후방지역 사단급이하,27-Jan,통신/전자,전술통신체계,차세대,Advanced Tactical Datalink System (ATDS),24-Jun,same,2.5,high,미군이 2024년 배치한 고급 전술 데이터 링크 시스템(ATDS)은 한국 시스템의 ...
3,UAM (도심항공교통),UAM (도심항공교통),28-Jun,항공/공군,도심 UAM 통합운용 시스템,실증 단계,Urban Air Mobility (UAM) Integrated Operations...,24-Apr,same,4.2,high,미국은 2020년대 초부터 UAM 통합 운영 시스템 개발 및 테스트를 활발히 진행해...
4,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",쇄빙선,26-Jun,해상/해군,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",차세대,Arktika-class icebreaker,Dec-78,same,47.5,high,미국이 1978년에 배치한 Arktika급 쇄빙선은 한국 시스템과 유사한 3MW급 ...
...,...,...,...,...,...,...,...,...,...,...,...,...
231,"K1A 기관단총, K-15 경기관총, K2C1 소총","K1A 기관단총, K-15 경기관총, K2C1 소총",20-Jun,육상/지상,"피카티니 레일 일체형 총열덮개, 전방 손잡이, 조절식 개머리",3세대,M4 Carbine,03-Jan,same,17.4,high,2003년에 미군에 도입된 M4 카빈은 한국의 K2C1 소총과 피카티니 레일 통합 ...
232,9mm SMART 권총,9mm SMART 권총,20-Jun,육상/지상,"스마트 모듈, 비살상탄 사용",신형,Sig Sauer P320 X-Series,17-Jan,same,3.4,high,2017년에 출시된 Sig Sauer P320 X-Series 권총은 한국의 9mm...
233,"['중형전술차량', '차기 표준차량(2.5톤/5톤급)']","중형전술차량, 차기 표준차량(2.5톤/5톤급)",21-Jun,육상/지상,"AI 기반 초연결 지상전투체계, 드론봇·무인기 등 감시정찰 자산, 통합 지휘망",미래,Autonomous Ground Vehicle (AGV),20-Jul,same as Korean,0.9,medium,미국은 2000년대 초반부터 군사용 자율주행 지상 차량 기술을 개발해왔다. 자율주행...
234,"['K1A 기관단총', 'K-15 경기관총', 'K2C1 자동소총', 'KSPW(K...","K1A 기관단총, K-15 경기관총, K2C1 자동소총",19-Aug,육상/지상,"소총, 기관총, 자동소총",3세대 소화기 무기,M4A1 Carbine,11-Aug,same,8.0,high,2011년 미 육군에 도입된 M4A1 카빈은 한국의 K2C1 돌격 소총과 동등한 시...
235,"인공지능(AI), 스마트 안전관리 체계",AI,19-Aug,육상/지상,"인공지능(AI), 스마트 안전관리 체계",AI,Automated Threat Awareness and Response System...,17-Sep,same,1.9,high,"한국 시스템의 AI 기반 위협 감지, 스마트 안전 관리, 사고 대응 및 자살 예방 ..."

In [11]:
df2[df2['domain'] == '기타']

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
35,"차세대 디젤엔진 DX05, DX08","차세대 디젤엔진 DX05, DX08",24-Nov,기타,차세대 디젤엔진,최신,Cummins X15 Efficiency Series Diesel Engine,17-Jan,same,7.8,high,2017년 도입된 Cummins X15 Efficiency Series 디젤 엔진은...
45,초거대 AI 인프라,NaN,24-Aug,기타,초거대 AI 인프라,차세대 AI,DARPA Artificial Intelligence Infrastructure (...,22-Jun,same,2.2,high,한국 시스템 설명은 2022년 6월 미국에서 최초 운용된 DAII의 기능과 일치합니...
79,자동 및 자율 측정 시스템,NaN,24-Feb,기타,자동 및 자율 측정 시스템,최신,Automated and Autonomous Measurement System (A...,21-Sep,same,2.4,high,미국은 첨단 청색 레이저 기술과 프로그래밍을 활용하여 6자유도 프로빙 및 스캐닝 기...
98,초고효율 HJT(이종접합 기술) 태양전지,태양전지,2026-01,기타,초고효율 HJT(이종접합 기술) 태양전지,차세대 기술,SunPower Maxeon 6 Solar Panels,21-Jun,same,4.5,high,2021년 출시된 SunPower Maxeon 6 태양전지는 HJT 기술을 사용하여...
124,수소모빌리티 통합형 수소충전소,"수소모빌리티 (수소차, 수소트램, 수소드론, 수소이륜차, 수소건설기계)",22-Nov,기타,수소충전소,최초,Hydrogen Fueling Station,15-Aug,same,7.2,high,"미국은 2000년대 초부터 수소 연료 공급 인프라 구축에 적극적으로 나서왔으며, 2..."
141,한국형 발전용 가스터빈,발전용 가스터빈,23-Jul,기타,한국형 발전용 가스터빈(H급: 터빈 효율 40%이상),독자개발 5번째 국가,GE LM6000 Gas Turbine,Jun-95,same,28.1,high,"GE LM6000은 1995년에 배치된 상용 가스 터빈 엔진으로, 약 40%의 열효..."
172,AI 기반 자동차 수리비 자동견적 시스템 'AOS 알파',해당없음,20-Jan,기타,"AI 기반 자동차 수리비 자동견적 시스템 'AOS 알파', MSA 기반 표준화된 보...",차세대,Allstate QuickFoto Claim,15-Jun,same,4.6,high,2015년 출시된 올스테이트 퀵포토 클레임 모바일 앱은 차량 피해 사진 제출과 수리...
194,수소 충전 인프라,수소 충전 인프라,21-Mar,기타,"수소 추출기, 압축기, 디스펜서",국산화 기술 개발,Hydrogen Fueling Infrastructure,15-Jun,same,5.8,high,미국 에너지부의 수소 및 연료전지 기술 사무소는 2000년대 초반부터 전국적인 수소...
205,"['적외선 분광기의 이동 반사경 틸트 보상시스템', '적외선 영상센서와 스마트폰을 ...","휴대용 원격 유독가스 누출 감시 장비, 드론 탑재형 조기 경보 시스템",22-Sep,기타,적외선 분광기의 이동 반사경 틸트 보상시스템,민간/산업용 기술 수준,Portable Methane Gas Leak Detector,19-Jun,same,3.2,high,"미국은 적외선 분광, 실시간 모니터링, 경량 설계 등 한국 시스템과 유사한 기능을 ..."

In [12]:
df2['domain'][35] = '육상/지상'
df2['domain'][35]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\731158016.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][35] = '육상/지상'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\731158016.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][35] = '육상/지상'

'육상/지상'

In [13]:
df2['domain'][141] = '항공/공군'
df2['domain'][141]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\1352876961.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][141] = '항공/공군'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\1352876961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][141] = '항공/공군'

'항공/공군'

In [14]:
df2['domain'][172] = '육상/지상'
df2['domain'][172]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2533425094.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][172] = '육상/지상'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2533425094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][172] = '육상/지상'

'육상/지상'

In [15]:
df2['domain'][45] = '신기술'
df2['domain'][79] = '신기술'
df2['domain'][98] = '신기술'
df2['domain'][124] = '신기술'
df2['domain'][194] = '신기술'
df2['domain'][205] = '신기술'

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][45] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][45] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][79] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][79] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][98] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][98] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][124] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][124] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][194] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][194] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][205] = '신기술'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\2511639059.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][205] = '신기술'

In [17]:
# df2[df2['domain'] == '기타']
df2[df2['domain'] == '신기술']

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
45,초거대 AI 인프라,NaN,24-Aug,신기술,초거대 AI 인프라,차세대 AI,DARPA Artificial Intelligence Infrastructure (...,22-Jun,same,2.2,high,한국 시스템 설명은 2022년 6월 미국에서 최초 운용된 DAII의 기능과 일치합니...
79,자동 및 자율 측정 시스템,NaN,24-Feb,신기술,자동 및 자율 측정 시스템,최신,Automated and Autonomous Measurement System (A...,21-Sep,same,2.4,high,미국은 첨단 청색 레이저 기술과 프로그래밍을 활용하여 6자유도 프로빙 및 스캐닝 기...
98,초고효율 HJT(이종접합 기술) 태양전지,태양전지,2026-01,신기술,초고효율 HJT(이종접합 기술) 태양전지,차세대 기술,SunPower Maxeon 6 Solar Panels,21-Jun,same,4.5,high,2021년 출시된 SunPower Maxeon 6 태양전지는 HJT 기술을 사용하여...
124,수소모빌리티 통합형 수소충전소,"수소모빌리티 (수소차, 수소트램, 수소드론, 수소이륜차, 수소건설기계)",22-Nov,신기술,수소충전소,최초,Hydrogen Fueling Station,15-Aug,same,7.2,high,"미국은 2000년대 초부터 수소 연료 공급 인프라 구축에 적극적으로 나서왔으며, 2..."
171,수소 연료전지,NaN,21-Jul,신기술,수소 연료전지,상용화 단계,Plug-in Hybrid Tactical Generator (PHTG),18-Apr,same,3.2,high,미국의 플러그인 하이브리드 전술 발전기(PHTG)는 PEMFC(고분자 전해질 연료 ...
194,수소 충전 인프라,수소 충전 인프라,21-Mar,신기술,"수소 추출기, 압축기, 디스펜서",국산화 기술 개발,Hydrogen Fueling Infrastructure,15-Jun,same,5.8,high,미국 에너지부의 수소 및 연료전지 기술 사무소는 2000년대 초반부터 전국적인 수소...
205,"['적외선 분광기의 이동 반사경 틸트 보상시스템', '적외선 영상센서와 스마트폰을 ...","휴대용 원격 유독가스 누출 감시 장비, 드론 탑재형 조기 경보 시스템",22-Sep,신기술,적외선 분광기의 이동 반사경 틸트 보상시스템,민간/산업용 기술 수준,Portable Methane Gas Leak Detector,19-Jun,same,3.2,high,"미국은 적외선 분광, 실시간 모니터링, 경량 설계 등 한국 시스템과 유사한 기능을 ..."

In [ ]:
# df2['domain'][216] = '지상/육상'
df2.head(217)
df2['domain'][214] = '육상/지상'
df2['domain'][214]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\1499873853.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['domain'][214] = '육상/지상'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_15644\1499873853.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['domain'][214] = '육상/지상'

'육상/지상'

In [ ]:
df2[df2['domain'] == '육상/지상']
df2['domain'][38] = '육상/지상'
df2['domain'][210] = '육상/지상'
df2['domain'][210]

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
9,"AI 기반 GOP 과학화경계작전 시스템, 교육용 드론",GOP(경계작전)대대,25-Sep,육상/지상,"AI 기반 객체 인식/분석 기술, 상용 교육용 드론",신기술 시범 적용 단계,RQ-11 Raven,07-May,same,18.3,high,RQ-11 Raven은 2007년부터 미군에서 운용 중인 소형 경량 무인항공기(UA...
19,정밀 용접 휴머노이드,조선/조선소,27-Jan,육상/지상,정밀 용접 휴머노이드,차세대,Automated Welding System for Shipbuilding (AWSS),25-Apr,same,1.8,high,"미국은 조선 자동화 및 로봇 분야의 선도국이며, 2020년대 중반에 개발된 AWSS..."
21,차세대 신모델,차세대 신모델 건설장비,25-Apr,육상/지상,"수소, 전기 등 친환경 동력원 활용 기술",차세대,Caterpillar M545 Electric Excavator,22-Jun,same,2.8,high,캐터필러 M545 전기 굴삭기는 수소 및 전기 추진 기술을 활용하는 콤팩트한 전기 ...
25,수소엔진,대형트럭,27-Jan,육상/지상,수소엔진 (HX12),신기술,M977 HEMTT,Jul-83,same,43.5,high,"M977 HEMTT는 미국 육군에서 사용하는 대형 군용 트럭으로, 수소 엔진을 탑재..."
35,"차세대 디젤엔진 DX05, DX08","차세대 디젤엔진 DX05, DX08",24-Nov,육상/지상,차세대 디젤엔진,최신,Cummins X15 Efficiency Series Diesel Engine,17-Jan,same,7.8,high,2017년 도입된 Cummins X15 Efficiency Series 디젤 엔진은...
36,적외선차폐연막통,지상용 및 수상용,25-Jan,육상/지상,적외선차폐연막통,2세대,AN/CMU-150 Vehicular Obscurant System,Sep-90,same,34.3,high,1980년대 후반에 개발된 AN/CMU-150 Vehicular Obscurant ...
38,"['LAH (차륜형장갑차)', '미르온', '우레', '천무용 230mm급 무유도탄...",LAH (차륜형장갑차),24-Oct,육상/지상,미르온,최신예/첨단,Stryker,03-Apr,more advanced than Korean,21.5,high,"2003년 배치된 미국의 Stryker 장갑 차량은 센서, 통신, 무기 시스템 등이..."
50,"['아리에테 전차 개량', 'KF-51 판터 공동생산', '신형 링스 보병전투차량']","아리에테 전차, KF-51 판터, KF-41 링스 보병전투차량",24-Jul,육상/지상,"주전차(MBT) 및 보병 전투 시스템(AICS) 개발, 전자 제품군 및 무기 통합",차세대 최첨단 전투 차량,M1 Abrams Main Battle Tank,Jul-80,same,44.0,high,1980년 미군에 처음 배치된 M1 에이브럼스 주력 전차는 한국에서 개발된 아리에테...
62,차륜형장갑차,K808 차륜형장갑차,24-May,육상/지상,차륜형장갑차 기술,2세대,M1117 Armored Security Vehicle,01-Jun,same,22.9,high,"M1117 장갑 경비차는 2001년 미국에서 처음 배치되었으며, 한국의 K808과 ..."
64,KTX-청룡,KTX-청룡,24-Apr,육상/지상,동력분산식 고속철도 기술,신형,Acela Express,Dec-00,same,23.3,high,아셀라 익스프레스(Acela Express)는 미국 북동부 지역에서 암트랙(Amtr...
99,AI 자율주행 순찰 로봇,HA순찰로봇,24-Jan,육상/지상,AI 자율주행 기술,2.5세대,Throwbot XT,21-Mar,same,2.8,high,Throwbot XT는 정찰 및 감시를 위해 사용되는 소형 원격 조종 지상 로봇으로...
113,캐터필러 C9.3 엔진,타이곤 차륜형 장갑차,23-Jan,육상/지상,캐터필러 C9.3 엔진,3세대 차륜형 장갑차,M1126 Stryker Infantry Carrier Vehicle,02-Aug,same,20.4,high,M1126 스트라이커 보병 수송 차량은 미국의 한국 태곤 차륜 장갑 차량과 동등한 ...
126,동력분산식 고속열차 EMU-320,동력분산식 고속열차 EMU-320,22-Sep,육상/지상,동력분산식 고속열차 시스템,320km/h 고속열차,Amtrak Acela Express,Dec-00,same,21.8,high,2000년 도입된 Amtrak Acela Express는 최대 속도 150mph(2...
130,대테러작전용 다족보행로봇,다족보행로봇,24-Jun,육상/지상,"4족 보행 로봇, 원격조종장치, 임무장비 (로봇팔, 원격무장통제장치, 섬광폭음탄 및...",초기 단계,Legged Squad Support System (LS3),13-Oct,same,10.7,high,DARPA와 Boston Dynamics가 개발한 Legged Squad Suppo...
162,양면발전 태양광 기술,태양광 모듈,20-May,육상/지상,양면발전 태양광 기술,상용화 단계,SunPower X-Series Residential Solar Panels,17-Mar,same,3.2,high,2017년 미국에 처음 배치된 SunPower X-시리즈 주거용 태양 전지판은 최대...
172,AI 기반 자동차 수리비 자동견적 시스템 'AOS 알파',해당없음,20-Jan,육상/지상,"AI 기반 자동차 수리비 자동견적 시스템 'AOS 알파', MSA 기반 표준화된 보...",차세대,Allstate QuickFoto Claim,15-Jun,same,4.6,high,2015년 출시된 올스테이트 퀵포토 클레임 모바일 앱은 차량 피해 사진 제출과 수리...
183,다목적무인차량,6x6 다목적무인차량,21-Jul,육상/지상,인공지능 기반 자율주행 및 원격주행 기술,첨단/최신 기술,Autonomous Resupply Vehicle (ARV),19-May,same,2.2,high,미 육군은 2010년대 중반부터 한국의 6x6 다목적 무인차량과 유사한 자율주행 보...
188,Machine Control Excavator,굴착기,21-Feb,육상/지상,머신컨트롤(Machine Control),반자율,Caterpillar D8T Dozer with Grade Control,06-Jul,same,14.6,high,"캐터필러 D8T 도저는 실시간 현장 감지, 자동 평탄화, 굴착 기능 등 한국 시스템..."
197,기가 철근,건축 구조물,20-Dec,육상/지상,기가 철근,초고강도 철근 (1세대),High-Strength Steel Reinforcement Bars,15-Jun,same,5.5,high,미국은 대규모 건설 프로젝트에 사용되는 고강도 철근 개발을 선도해왔습니다. 가용한 ...
200,차세대 군용차 표준 플랫폼,차세대 군용차 표준 플랫폼,24-Jan,육상/지상,2.5톤 및 5톤 중형표준차량 개발,차세대,FMTV (Family of Medium Tactical Vehicles),Jan-96,same,28.0,high,미국의 FMTV 프로그램은 1990년대 초반에 시작되었고 1996년 첫 모델이 배치...
203,수소전기트럭,엑시언트 수소전기트럭,20-Oct,육상/지상,수소연료전지,양산,Nikola Tre FCEV,21-Apr,same,-0.5,high,니콜라 Tre FCEV는 한국의 엑시언트 수소 연료전지 트럭에 해당하는 미국 제품입...
204,차세대 전술트럭,차세대 전술트럭,20-Sep,육상/지상,"7리터급 디젤엔진, 자동변속기, ABS, ASR, 후방주차보조, 첨단 운전자 보조 ...",차세대,Family of Medium Tactical Vehicles (FMTV),Mar-95,same,25.5,high,2.5톤과 5톤 트럭 가족으로 구성된 미국 FMTV 프로그램은 1995년에 배치되었...
208,컴뱃셔츠,전투복,11-Jun,육상/지상,컴뱃셔츠,21세기 현대전 기술 수준,Army Combat Uniform (ACU),05-Jun,same,6.0,high,2005년 미국 육군이 도입한 육군 전투복(ACU)은 한국군 전투셔츠와 유사한 기능...
209,수소전기트램,수소전기트램,21-Dec,육상/지상,"수소전기트램, 수소충전소",실증사업 단계,Proterra ZX5 electric bus,16-Apr,same,5.7,high,프로테라 ZX5 전기 버스는 한국의 수소 전기 트램과 가장 유사한 미국의 대안입니다...
210,적외선차폐연막통,none specified,20-Aug,육상/지상,적외선차폐연막통,신형,AN/VLQ-6 Vehicle-Mounted Obscurant System (VMOS),Dec-94,same,25.7,high,"AN/VLQ-6 VMOS는 미 육군의 차량 탑재형 적외선/시각 은폐 시스템으로, 시..."
214,"감시·정찰, 미사일, 한국형 미사일방어, 지상전력, 해상·상륙전력, 공중?우주전력,...","K2 전차, KF-21 전투기, 세종대왕급 구축함, 도산안창호급 잠수함",25-Jun,육상/지상,"AESA 레이더, 1500마력 디젤엔진, 리튬이온 배터리, 수소연료전지","4.5세대 전투기, 3세대 전차, 3세대 잠수함",M1A2 Abrams MBT,Jun-92,same,33.0,high,"M1A2 애브럼즈 주력전차는 1992년 미국이 처음 배치했으며, 한국의 K2 블랙팬..."
219,"['센서/통신', '무기/방어체계', '재료/제조', '항공기']",중형전술트럭,20-Mar,육상/지상,"센서/통신, 재료/제조",2세대(현대화),M1083A1 Family of Medium Tactical Vehicles (FMTV),01-Nov,same,18.3,high,M1083A1 FMTV는 2001년 미군이 배치한 2세대 중형 전술 트럭 플랫폼으로...
222,민수용 차량,민수용 차량,12-Jan,육상/지상,비표준차량,현대화 시도,HMMWV (High Mobility Multipurpose Wheeled Vehi...,Aug-85,same,26.4,high,"1980년대 중반에 도입된 HMMWV는 4륜구동, 런플랫 타이어, 전술 병력 수송 ..."
223,수소전기버스,경찰 수소전기버스,2021-01,육상/지상,수소연료전지,최신,GILLIG Hybrid-Electric Bus,14-Jan,same,6.9,high,2014년 도입된 GILLIG 하이브리드-전기 버스는 95kW 연료전지 스택과 고속...
224,중형표준차량,중형표준차량,19-Nov,육상/지상,"4륜구동, 방수 설계, 높은 최저지상고",3세대,M1151 HMMWV,Jun-84,more advanced than Korean,35.4,high,"1984년 도입된 M1151 HMMWV는 4륜구동, 수중 주행 능력, 고출력 엔진 ..."
227,차세대 중형표준차량 및 5톤 방탄킷 차량,"중형표준차량, 5톤 방탄킷 차량",24-Jan,육상/지상,"7리터급 디젤 엔진, 자동변속기, ABS, ASR, 후방주차보조, 첨단 운전자 보조...",차세대,HEMTT A4 (Heavy Expanded Mobility Tactical Truck),19-Mar,same,4.8,high,"HEMTT A4는 미국 육군의 주력 5톤 전술 트럭으로, 한국 5톤 장갑차와 유사한..."
231,"K1A 기관단총, K-15 경기관총, K2C1 소총","K1A 기관단총, K-15 경기관총, K2C1 소총",20-Jun,육상/지상,"피카티니 레일 일체형 총열덮개, 전방 손잡이, 조절식 개머리",3세대,M4 Carbine,03-Jan,same,17.4,high,2003년에 미군에 도입된 M4 카빈은 한국의 K2C1 소총과 피카티니 레일 통합 ...
232,9mm SMART 권총,9mm SMART 권총,20-Jun,육상/지상,"스마트 모듈, 비살상탄 사용",신형,Sig Sauer P320 X-Series,17-Jan,same,3.4,high,2017년에 출시된 Sig Sauer P320 X-Series 권총은 한국의 9mm...
233,"['중형전술차량', '차기 표준차량(2.5톤/5톤급)']","중형전술차량, 차기 표준차량(2.5톤/5톤급)",21-Jun,육상/지상,"AI 기반 초연결 지상전투체계, 드론봇·무인기 등 감시정찰 자산, 통합 지휘망",미래,Autonomous Ground Vehicle (AGV),20-Jul,same as Korean,0.9,medium,미국은 2000년대 초반부터 군사용 자율주행 지상 차량 기술을 개발해왔다. 자율주행...
234,"['K1A 기관단총', 'K-15 경기관총', 'K2C1 자동소총', 'KSPW(K...","K1A 기관단총, K-15 경기관총, K2C1 자동소총",19-Aug,육상/지상,"소총, 기관총, 자동소총",3세대 소화기 무기,M4A1 Carbine,11-Aug,same,8.0,high,2011년 미 육군에 도입된 M4A1 카빈은 한국의 K2C1 돌격 소총과 동등한 시...
235,"인공지능(AI), 스마트 안전관리 체계",AI,19-Aug,육상/지상,"인공지능(AI), 스마트 안전관리 체계",AI,Automated Threat Awareness and Response System...,17-Sep,same,1.9,high,"한국 시스템의 AI 기반 위협 감지, 스마트 안전 관리, 사고 대응 및 자살 예방 ..."

In [30]:
df2['domain'].value_counts()

domain
항공/공군     80
해상/해군     50
통신/전자     37
육상/지상     36
우주        17
미사일/방공     9
신기술        7
Name: count, dtype: int64

In [16]:
df2

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
0,"피지컬 AI, 온디바이스 AI","드론, 로봇",25-Dec,통신/전자,"피지컬 AI, 온디바이스 AI",차세대,Reaper/Predator Unmanned Aerial Vehicles (UAVs),09-Mar,same,16.8,high,"미국은 무인기 기술의 글로벌 리더이며, Reaper/Predator UAV는 200..."
1,Dagaie NG,함정,25-Nov,해상/해군,대함 미사일 기만체계,최신,AN/ALE-47 Countermeasures Dispensing System,Sep-88,same,37.2,high,AN/ALE-47 대응수단 분배 시스템은 1988년부터 미군에 의해 사용되어 왔으며...
2,후방지역 사단급이하 전술통신체계,후방지역 사단급이하,27-Jan,통신/전자,전술통신체계,차세대,Advanced Tactical Datalink System (ATDS),24-Jun,same,2.5,high,미군이 2024년 배치한 고급 전술 데이터 링크 시스템(ATDS)은 한국 시스템의 ...
3,UAM (도심항공교통),UAM (도심항공교통),28-Jun,항공/공군,도심 UAM 통합운용 시스템,실증 단계,Urban Air Mobility (UAM) Integrated Operations...,24-Apr,same,4.2,high,미국은 2020년대 초부터 UAM 통합 운영 시스템 개발 및 테스트를 활발히 진행해...
4,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",쇄빙선,26-Jun,해상/해군,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",차세대,Arktika-class icebreaker,Dec-78,same,47.5,high,미국이 1978년에 배치한 Arktika급 쇄빙선은 한국 시스템과 유사한 3MW급 ...
...,...,...,...,...,...,...,...,...,...,...,...,...
231,"K1A 기관단총, K-15 경기관총, K2C1 소총","K1A 기관단총, K-15 경기관총, K2C1 소총",20-Jun,육상/지상,"피카티니 레일 일체형 총열덮개, 전방 손잡이, 조절식 개머리",3세대,M4 Carbine,03-Jan,same,17.4,high,2003년에 미군에 도입된 M4 카빈은 한국의 K2C1 소총과 피카티니 레일 통합 ...
232,9mm SMART 권총,9mm SMART 권총,20-Jun,육상/지상,"스마트 모듈, 비살상탄 사용",신형,Sig Sauer P320 X-Series,17-Jan,same,3.4,high,2017년에 출시된 Sig Sauer P320 X-Series 권총은 한국의 9mm...
233,"['중형전술차량', '차기 표준차량(2.5톤/5톤급)']","중형전술차량, 차기 표준차량(2.5톤/5톤급)",21-Jun,육상/지상,"AI 기반 초연결 지상전투체계, 드론봇·무인기 등 감시정찰 자산, 통합 지휘망",미래,Autonomous Ground Vehicle (AGV),20-Jul,same as Korean,0.9,medium,미국은 2000년대 초반부터 군사용 자율주행 지상 차량 기술을 개발해왔다. 자율주행...
234,"['K1A 기관단총', 'K-15 경기관총', 'K2C1 자동소총', 'KSPW(K...","K1A 기관단총, K-15 경기관총, K2C1 자동소총",19-Aug,육상/지상,"소총, 기관총, 자동소총",3세대 소화기 무기,M4A1 Carbine,11-Aug,same,8.0,high,2011년 미 육군에 도입된 M4A1 카빈은 한국의 K2C1 돌격 소총과 동등한 시...
235,"인공지능(AI), 스마트 안전관리 체계",AI,19-Aug,육상/지상,"인공지능(AI), 스마트 안전관리 체계",AI,Automated Threat Awareness and Response System...,17-Sep,same,1.9,high,"한국 시스템의 AI 기반 위협 감지, 스마트 안전 관리, 사고 대응 및 자살 예방 ..."

In [24]:
# df2['kr_date'] = df2['kr_date'].astype(str)
# df2['us_date'] = df2['us_date'].astype(str)
df2['kr_date']

0      25-Dec
1      25-Nov
2      27-Jan
3      28-Jun
4      26-Jun
        ...
231    20-Jun
232    20-Jun
233    21-Jun
234    19-Aug
235    19-Aug
Name: kr_date, Length: 236, dtype: object

In [22]:
df2.to_csv("진짜 정돈된 것2.csv", index = False, encoding = "utf-8-sig")

In [4]:
# import sys
# print(sys.executable)
# % 기호는 현재 노트북이 사용하는 커널에 직접 설치하라는 매직 명령어입니다.
%pip install matplotlib numpy

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.4.0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 8.1/8.1 MB 76.0 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 72.2 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.1.0-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 80.3 MB/s  0:00:00
Using cached pyparsing-3.3.1-py3-none-any.whl (121 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 pillow-12.1.0 pyparsing-3.3.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\user\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [9]:
rel = pd.read_csv("진짜 정돈된 것.csv")

df = pd.DataFrame(rel)
df

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
0,"피지컬 AI, 온디바이스 AI","드론, 로봇",25-Dec,통신/전자,"피지컬 AI, 온디바이스 AI",차세대,Reaper/Predator Unmanned Aerial Vehicles (UAVs),09-Mar,same,16.8,high,"미국은 무인기 기술의 글로벌 리더이며, Reaper/Predator UAV는 200..."
1,Dagaie NG,함정,25-Nov,해상/해군,대함 미사일 기만체계,최신,AN/ALE-47 Countermeasures Dispensing System,Sep-88,same,37.2,high,AN/ALE-47 대응수단 분배 시스템은 1988년부터 미군에 의해 사용되어 왔으며...
2,후방지역 사단급이하 전술통신체계,후방지역 사단급이하,2027-01,통신/전자,전술통신체계,차세대,Advanced Tactical Datalink System (ATDS),24-Jun,same,2.5,high,미군이 2024년 배치한 고급 전술 데이터 링크 시스템(ATDS)은 한국 시스템의 ...
3,UAM (도심항공교통),UAM (도심항공교통),28-Jun,항공/공군,도심 UAM 통합운용 시스템,실증 단계,Urban Air Mobility (UAM) Integrated Operations...,24-Apr,same,4.2,high,미국은 2020년대 초부터 UAM 통합 운영 시스템 개발 및 테스트를 활발히 진행해...
4,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",쇄빙선,26-Jun,해상/해군,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",차세대,Arktika-class icebreaker,Dec-78,same,47.5,high,미국이 1978년에 배치한 Arktika급 쇄빙선은 한국 시스템과 유사한 3MW급 ...
...,...,...,...,...,...,...,...,...,...,...,...,...
231,"K1A 기관단총, K-15 경기관총, K2C1 소총","K1A 기관단총, K-15 경기관총, K2C1 소총",20-Jun,육상/지상,"피카티니 레일 일체형 총열덮개, 전방 손잡이, 조절식 개머리",3세대,M4 Carbine,03-Jan,same,17.4,high,2003년에 미군에 도입된 M4 카빈은 한국의 K2C1 소총과 피카티니 레일 통합 ...
232,9mm SMART 권총,9mm SMART 권총,20-Jun,육상/지상,"스마트 모듈, 비살상탄 사용",신형,Sig Sauer P320 X-Series,17-Jan,same,3.4,high,2017년에 출시된 Sig Sauer P320 X-Series 권총은 한국의 9mm...
233,"['중형전술차량', '차기 표준차량(2.5톤/5톤급)']","중형전술차량, 차기 표준차량(2.5톤/5톤급)",21-Jun,육상/지상,"AI 기반 초연결 지상전투체계, 드론봇·무인기 등 감시정찰 자산, 통합 지휘망",미래,Autonomous Ground Vehicle (AGV),20-Jul,same as Korean,0.9,medium,미국은 2000년대 초반부터 군사용 자율주행 지상 차량 기술을 개발해왔다. 자율주행...
234,"['K1A 기관단총', 'K-15 경기관총', 'K2C1 자동소총', 'KSPW(K...","K1A 기관단총, K-15 경기관총, K2C1 자동소총",19-Aug,육상/지상,"소총, 기관총, 자동소총",3세대 소화기 무기,M4A1 Carbine,11-Aug,same,8.0,high,2011년 미 육군에 도입된 M4A1 카빈은 한국의 K2C1 돌격 소총과 동등한 시...
235,"인공지능(AI), 스마트 안전관리 체계",AI,19-Aug,육상/지상,"인공지능(AI), 스마트 안전관리 체계",AI,Automated Threat Awareness and Response System...,17-Sep,same,1.9,high,"한국 시스템의 AI 기반 위협 감지, 스마트 안전 관리, 사고 대응 및 자살 예방 ..."

1. domain 별로 (최신의) 연구가 어디/언제까지 진행됐는지 비교를 통해 주력 산업군과 비주력 산업군 도출

In [ ]:
df.copy()

,kr_technology,kr_platform,kr_date,domain,core_technology,tech_generation,us_equivalent,us_date,us_tech_level,gap_years,confidence,reasoning
0,"피지컬 AI, 온디바이스 AI","드론, 로봇",25-Dec,통신/전자,"피지컬 AI, 온디바이스 AI",차세대,Reaper/Predator Unmanned Aerial Vehicles (UAVs),09-Mar,same,16.8,high,"미국은 무인기 기술의 글로벌 리더이며, Reaper/Predator UAV는 200..."
1,Dagaie NG,함정,25-Nov,해상/해군,대함 미사일 기만체계,최신,AN/ALE-47 Countermeasures Dispensing System,Sep-88,same,37.2,high,AN/ALE-47 대응수단 분배 시스템은 1988년부터 미군에 의해 사용되어 왔으며...
2,후방지역 사단급이하 전술통신체계,후방지역 사단급이하,2027-01,통신/전자,전술통신체계,차세대,Advanced Tactical Datalink System (ATDS),24-Jun,same,2.5,high,미군이 2024년 배치한 고급 전술 데이터 링크 시스템(ATDS)은 한국 시스템의 ...
3,UAM (도심항공교통),UAM (도심항공교통),28-Jun,항공/공군,도심 UAM 통합운용 시스템,실증 단계,Urban Air Mobility (UAM) Integrated Operations...,24-Apr,same,4.2,high,미국은 2020년대 초부터 UAM 통합 운영 시스템 개발 및 테스트를 활발히 진행해...
4,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",쇄빙선,26-Jun,해상/해군,"프로펠러-모터 직결형 선회식 전기추진기(POD, Podded Propulsor)",차세대,Arktika-class icebreaker,Dec-78,same,47.5,high,미국이 1978년에 배치한 Arktika급 쇄빙선은 한국 시스템과 유사한 3MW급 ...
...,...,...,...,...,...,...,...,...,...,...,...,...
231,"K1A 기관단총, K-15 경기관총, K2C1 소총","K1A 기관단총, K-15 경기관총, K2C1 소총",20-Jun,육상/지상,"피카티니 레일 일체형 총열덮개, 전방 손잡이, 조절식 개머리",3세대,M4 Carbine,03-Jan,same,17.4,high,2003년에 미군에 도입된 M4 카빈은 한국의 K2C1 소총과 피카티니 레일 통합 ...
232,9mm SMART 권총,9mm SMART 권총,20-Jun,육상/지상,"스마트 모듈, 비살상탄 사용",신형,Sig Sauer P320 X-Series,17-Jan,same,3.4,high,2017년에 출시된 Sig Sauer P320 X-Series 권총은 한국의 9mm...
233,"['중형전술차량', '차기 표준차량(2.5톤/5톤급)']","중형전술차량, 차기 표준차량(2.5톤/5톤급)",21-Jun,육상/지상,"AI 기반 초연결 지상전투체계, 드론봇·무인기 등 감시정찰 자산, 통합 지휘망",미래,Autonomous Ground Vehicle (AGV),20-Jul,same as Korean,0.9,medium,미국은 2000년대 초반부터 군사용 자율주행 지상 차량 기술을 개발해왔다. 자율주행...
234,"['K1A 기관단총', 'K-15 경기관총', 'K2C1 자동소총', 'KSPW(K...","K1A 기관단총, K-15 경기관총, K2C1 자동소총",19-Aug,육상/지상,"소총, 기관총, 자동소총",3세대 소화기 무기,M4A1 Carbine,11-Aug,same,8.0,high,2011년 미 육군에 도입된 M4A1 카빈은 한국의 K2C1 돌격 소총과 동등한 시...
235,"인공지능(AI), 스마트 안전관리 체계",AI,19-Aug,육상/지상,"인공지능(AI), 스마트 안전관리 체계",AI,Automated Threat Awareness and Response System...,17-Sep,same,1.9,high,"한국 시스템의 AI 기반 위협 감지, 스마트 안전 관리, 사고 대응 및 자살 예방 ..."

1. domain 별로 (최신의) 연구가 어디/언제까지 진행됐는지 비교를 통해 주력 산업군과 비주력 산업군 도출

2. gap_years 비교를 통해 우리나라가 밀고있는 산업군 top3

3. (2)를 통해 도출된 결과의 기술 키워드 중심으로 미국에서 연구하고 있는 연구물들(기술 키워드 매칭 -> 미국 연구성과 분석)

2. gap_years 비교를 통해 우리나라가 밀고있는 산업군 top3

3. (2)를 통해 도출된 결과의 기술 키워드 중심으로 미국에서 연구하고 있는 연구물들(기술 키워드 매칭 -> 미국 연구성과 분석)