0. 필요 패키지 다운로드 및 임포트

In [300]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [301]:
import pandas as pd
import numpy as np

1. 시리즈Series

- 1차원 배열의 값에 각 값에 대응되는 인덱스를 부여할 수 있는 구조
- 시리즈 = 값 + 인덱스

- 인덱스 길이 == 데이터 길이
- 인덱스 값은 문자열, 시간, 날짜, 정수 등도 모두 가능

- 리스트 = 파이썬 기본 자료구조  VS. 시리즈 = 판다스의 1차원 자료구조

In [302]:
#1-1) 시리즈 생성

s = pd.Series([9904312, 3448737, 2890451, 2466052], index = ["서울", "부산", "인천", "대구"])
s

#인덱스화하여 응용 가능 -> 따라서 겹치지 않아야 함

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [303]:
#인덱스 지정하지 않으면 임의의 인덱스로 지정됨
s = pd.Series([9904312, 3448737, 2890451, 2466052])
s

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [304]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [305]:
s.values

array([9904312, 3448737, 2890451, 2466052])

In [306]:
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

- name 속성을 이용해 시리즈 데이터에 이름 붙임
- index.name 속성으로 시리즈의 인덱스에도 이름 붙임

In [307]:
s.name = "인구"
s.index.name = "도시"
s

도시
0    9904312
1    3448737
2    2890451
3    2466052
Name: 인구, dtype: int64

1-2) 시리즈 연산

- 시리즈는 벡터화 연산 가능
- 연산이 시리즈 값에만 적용, 인덱스 값은 변하지 않음

In [308]:
s / 1000000

도시
0    9.904312
1    3.448737
2    2.890451
3    2.466052
Name: 인구, dtype: float64

In [309]:
#리스트와 비교
lst = [1,2,3]
print("리스트연산\n")

리스트연산

1-3) 시리즈 인덱싱

In [310]:
#자료 순서 바꾸기
print(s[[0,3,1]])

print()

print(s[["서울", "대구", "부산"]])

도시
0    9904312
3    2466052
1    3448737
Name: 인구, dtype: int64

KeyError: "None of [Index(['서울', '대구', '부산'], dtype='object', name='도시')] are in the [index]"

In [ ]:
s[(250e4 < s) & (s < 500e4)]  #인구가 250만 초과, 500만 미만인 경우

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 슬라이싱 가능
- 문자열일 경우, 콜론(:) 뒤에 오는 값도 결과에 포함

In [ ]:
print(s[1:3])  #1번 인덱스부터 2번 인덱스까지(3 미포함)

print()

print(s["부산":"대구"])

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 라벨값이 영문 문자열인 경우 인덱스 라벨이 속성인 것처럼 점(.)을 이용해 해당 인덱스에 접근 가능

In [ ]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [ ]:
list(range(3))

[0, 1, 2]

In [ ]:
s0.a

np.int64(0)

In [ ]:
s0.c

np.int64(2)

1-4) 시리즈와 딕셔러니 자료형

- 시리즈 객체는 라벨 값에 의해 인덱싱이 가능, 실질적으로 인렉스 라벨 값을 키로 가지는 딕셔너리 자료형과 같다고 봄
- 딕셔너리 자료형에서 제공하는 in 연산, for 루프를 통한 각 원소릐 키와 값에 접근 가능

In [ ]:
"서울" in s  #인덱스 라벨 중에 서울이 있는가?

True

In [ ]:
"대전" in s  #인덱스 라벨 중에 대전이 있는가?

False

In [ ]:
for k, v in s.items():
    print("%s = %d" % (k, v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052

In [ ]:
#딕셔너리 객체에서 시리즈 만들기

s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 딕셔너리의 원소는 순서를 가지지 않으므로 시리즈의 데이털도 순서가 보장X
- 만약 순서를 정하고 싶다면 인덱스를 리스트로 지정해야 함

In [ ]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}, index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [ ]:
s2[1]

C:\Users\user\AppData\Local\Temp\ipykernel_10488\2825080482.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[1]

np.int64(9631482)

1-5) 인덱스 기반 연산

- 2015년도와 2010년도의

In [ ]:
#인덱스 같은 데이터에 대해서만 계산O
#***NaN(Not a Number, Not of Number)은 수치형 데이터가 없어서 계산된 결과가 없는 것, Null은 입력 아예 안된 것 (둘 다 혼용은 가능한데..... 좀 다르긴 함)***

ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [ ]:
#null 값 아닌 것 찾기

ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [ ]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [ ]:
#증가율 계산

rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

1-6) 데이터의 갱신, 추가, 삭제

- 인덱싱을 이용하면 딕셔너리처럼 데이터를 갱신Update 하거나 추가Add 가능

In [ ]:
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [ ]:
rs["대구"] = 1.41  #없던 것은 생기고, 있던 것은 새로 입력된 것으로 업데이트
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [ ]:
#데이터 삭제

del rs["대구"]
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

### 연습 문제 ###

In [ ]:
#1.
#(1) 임의로 두 개의 시리즈 객체를 만듦. 모두 문자열 인덱스를 가져야 하며, 두 시리즈에 공통적으로 포함되지 않는 라벨 있어야 함
#(2) 위에서 만든 두 시리즈 객체 이용해 사칙 연산

k1 = pd.Series({"백": 100, "이백": 200, "삼백": 300, "사백": 400}, index=["백", "이백", "삼백", "사백"])
k2 = pd.Series({"오백": 500, "육백": 600, "칠백": 700, "팔백": 800}, index=["오백", "육백", "칠백", "팔백"])

ressum = k1["백"] + k2["오백"]
resmin = k1["이백"] - k2["육백"]
resmul = k1["삼백"] * k2["칠백"]
resdiv = k1["사백"] / k2["팔백"]

print(ressum, resmin, resmul, resdiv)

600 -400 210000 0.5

In [ ]:
cost = pd.Series([1500, 5000, 3500, 3000, 1000], index=["칫솔", "고무장갑", "포카칩", "베이킹소다", "스펀지"])
r = pd.Series([5, 1, 3, 2, 5], index=["칫솔", "고무장갑", "포카칩", "베이킹소다", "뒤집개"])

res = cost * r
res

고무장갑      5000.0
뒤집개          NaN
베이킹소다     6000.0
스펀지          NaN
칫솔        7500.0
포카칩      10500.0
dtype: float64

2) 데이터 프레임DataFrame

- 2차원 리스트를 매개변수로 전달하는 구조
- 2차원이므로 행방향 인덱스index와 열방향 인덱스Column가 존재
- 데이터프레임은 열까지 추가되어 열Columns, 인덱스index, 값Values으로 구성
- 시리즈는 인덱스와 값으로 구성

In [ ]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)  #인덱스에 index의 값들을, 열에 columns의 값을 지정해서 출력하겠다는 의미

print('데이터프레임 출력 :')
print('-'*18)
print(df)

데이터프레임 출력 :
------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

In [ ]:
df1 = pd.DataFrame(values, columns = columns)
print(df1)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(df.index)
print(df.columns)
print(df.values)

Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3) 데이터프레임의 생성

-

In [ ]:
# 리스트로 생성하기
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]

df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#열 지정

df = pd.DataFrame(data, columns = ['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [ ]:
# 딕셔너리로 생성하기

data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]

df2 = pd.DataFrame(data)
df2

      2015     2010     2005     2000   지역  2010-2015 증가율
0  9904312  9631482  9762546  9853972  수도권         0.0283
1  3448737  3393191  3512547  3655437  경상권         0.0163
2  2890451  2632035  2517680  2466338  수도권         0.0982
3  2466052  2431774  2456016  2473990  경상권         0.0141

In [ ]:
df2 = pd.DataFrame(data, index = index, columns = columns)
print(df2)

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [ ]:
print(df2.index)  #현재 타입 = Object, 수정 불가한 상태. 수정하려면 타입을 바꾸고 수정해야 함
print(df2.columns)
print(df2.values)

Index(['서울', '부산', '인천', '대구'], dtype='object')
Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')
[['수도권' 9904312 9631482 9762546 9853972 0.0283]
 ['경상권' 3448737 3393191 3512547 3655437 0.0163]
 ['수도권' 2890451 2632035 2517680 2466338 0.0982]
 ['경상권' 2466052 2431774 2456016 2473990 0.0141]]

In [ ]:
#전치행렬 가능
df2.T

                    서울       부산       인천       대구
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [ ]:
df2  #df2 자체는 변하지 않음. 전치한 결과만 출력하는 게 .T

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

3-2) 열 데이터의 갱신, 추가, 삭제

- 데이터프레임은 열 시리즈의 딕셔너리로 볼 수 있으므로 열 단위로 데이터를 갱신, 추가, 삭제 가능

In [ ]:
#"2010-2015 증가율" 이라는 이름의 열 추가

df2["2010~2015 증가율"] = df2["2010-2015 증가율"] * 100
df2

     지역     2015     2010     2005     2000  2010-2015 증가율  2010~2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283           2.83
부산  경상권  3448737  3393191  3512547  3655437         0.0163           1.63
인천  수도권  2890451  2632035  2517680  2466338         0.0982           9.82
대구  경상권  2466052  2431774  2456016  2473990         0.0141           1.41

In [ ]:
# "2005-2010 증가율"이라는 이름의 열 추가
df2["2005-2010 증가율"] = ((df2["2010"] - df2["2005"]) / df2["2005"] * 100).round(3)
df2

,지역,2015,2010,2005,2000,2010-2015 증가율,2010~2015 증가율,2005-2010 증가율
서울,수도권,9904312,9631482,9762546,9853972,0.0283,2.83,-1.343
부산,경상권,3448737,3393191,3512547,3655437,0.0163,1.63,-3.398
인천,수도권,2890451,2632035,2517680,2466338,0.0982,9.82,4.542
대구,경상권,2466052,2431774,2456016,2473990,0.0141,1.41,-0.987

In [ ]:
#"2010~2015 증가율"이라는 이름의 열 삭제
del df2["2010~2015 증가율"]
df2

     지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283         -1.343
부산  경상권  3448737  3393191  3512547  3655437         0.0163         -3.398
인천  수도권  2890451  2632035  2517680  2466338         0.0982          4.542
대구  경상권  2466052  2431774  2456016  2473990         0.0141         -0.987

In [ ]:
#하나의 열만 인덱싱하면 시리즈 반환
df2["지역"]

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [ ]:
type(df2["지역"])

pandas.core.series.Series

In [ ]:
#여러 개의 열을 인덱싱하면 부분적인 데이터프레임이 반환
df2[["2010", "2015"]]

       2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [ ]:
type(df2[["2010", "2015"]])

pandas.core.frame.DataFrame

In [ ]:
#2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
df2[["2010"]]

       2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [ ]:
type(df2[["2010"]])

pandas.core.frame.DataFrame

In [ ]:
#문자열 라벨을 가지는 경우 정수 인덱스를 열 인덱싱에 사용X
df2[0]

KeyError: 0

In [ ]:
#열 인덱스가 정수형일 때 인덱스 값에 정수 사용O
df3 = pd.DataFrame(np.arange(12).reshape(3,4))
df3

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
(0,12,1)

In [ ]:
df3[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [ ]:
df3[[1,2]]

   1   2
0  1   2
1  5   6
2  9  10

3-4) 행 인덱싱

- 행 단위로 인덱싱 하고자 하면 항상 슬라이싱Slicing 사용
- 인덱스 값이 문자 라벨이면 라벨 슬라이싱 O

In [ ]:
df2

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [ ]:
df2[:1]

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283

In [ ]:
df2[1:2]

     지역     2015     2010     2005     2000  2010-2015 증가율
부산  경상권  3448737  3393191  3512547  3655437         0.0163

In [ ]:
df2[1:3]

     지역     2015     2010     2005     2000  2010-2015 증가율
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982

In [ ]:
df2["서울":"부산"]

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163

In [ ]:
#개별 데이터 인덱싱 / 열 라벨로 인덱싱 후 행 라벨로 인덱싱하면 원하는 개별 라벨 얻을 수 O
df2["2010"]["인천":"대구"]

인천    2632035
대구    2431774
Name: 2010, dtype: int64

### 연습 문제 ###

In [ ]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [ ]:
# (1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
math = pd.Series(data["수학"], index = index)
math
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
korEng = pd.DataFrame(df.T["국어":"영어"])
korEng
# (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df["세 과목 평균"] = (df["국어"] + df["수학"] + df["영어"]) / len(columns)
df
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
df["영어"]["방자"] = 80
df["세 과목 평균"] = round((df["국어"] + df["수학"] + df["영어"]) / len(columns), 2)  #round(식, 2) -> 계산되는 식을 소수점 2번째 자리까지 표사하기
df
# (5) 춘향의 점수를 데이터프레임으로 나타낸다.
choon = pd.DataFrame(df.T["춘향"])
choon
# (6) 향단의 점수를 시리즈로 나타낸다.
hyang = pd.Series(df.T["향단"])
hyang

C:\Users\user\AppData\Local\Temp\ipykernel_10944\2519121438.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["영어"]["방자"] = 80
C:\Users\user\AppData\Local\Temp\ipykernel_10944\2519121438.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["영어"]["방자"] = 80

국어         70.0
영어         60.0
수학         80.0
세 과목 평균    70.0
Name: 향단, dtype: float64

해설

In [ ]:
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
korEng2 = df[["국어","영어"]]
korEng2

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  80

In [ ]:
# (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df.loc["방자", "영어"] = 80
df["세 과목 평균"] = round((df["국어"] + df["수학"] + df["영어"]) / len(columns), 2)
df

    국어  영어  수학  세 과목 평균
춘향  80  90  90    86.67
몽룡  90  70  60    73.33
향단  70  60  80    70.00
방자  30  80  70    60.00

In [ ]:
# (5) 춘향의 점수를 데이터프레임으로 나타낸다.
df[:1]

    국어  영어  수학  세 과목 평균
춘향  80  90  90    86.67

In [ ]:
# (6) 향단의 점수를 시리즈로 나타낸다.
hyang = pd.Series(list(df[2:3].values), index = ["향단"])
hyang

향단    [70.0, 60.0, 80.0, 70.0]
dtype: object

4) 데이터프레임 조회하기

- df.head(n) : 앞 부분 n개만 보기
- df.tail(n) : 뒷 부분 n개만 보기
- df["열 이름"] : 해당 열 확인

In [ ]:
# 앞 부분 n개만 보기
print(df.head(3))

    국어  영어  수학  세 과목 평균
춘향  80  90  90    86.67
몽룡  90  70  60    73.33
향단  70  60  80    70.00

In [ ]:
# 뒷 부분 n개만 보기
print(df.tail(3))

    국어  영어  수학  세 과목 평균
몽룡  90  70  60    73.33
향단  70  60  80    70.00
방자  30  80  70    60.00

In [ ]:
#'국어'에 해당되는 열 보기
df["국어"]

춘향    80
몽룡    90
향단    70
방자    30
Name: 국어, dtype: int64

5) 외부 데이터 읽기

- Pandas는 CSV, 텍스트, Excel, SQL, HTML, JSON 등 다양한 데이터 파일을 읽어 데이터프레임 생성O

In [ ]:
df2 = pd.read_csv('RegularSeasonCompactResults.csv')
print(df2)

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0         1985      20     1228      81     1328      64    N      0
1         1985      25     1106      77     1354      70    H      0
2         1985      25     1112      63     1223      56    H      0
3         1985      25     1165      70     1432      54    H      0
4         1985      25     1192      86     1447      74    H      0
...        ...     ...      ...     ...      ...     ...  ...    ...
156084    2018     132     1153      56     1222      55    N      0
156085    2018     132     1172      58     1348      57    N      0
156086    2018     132     1209      74     1426      61    N      0
156087    2018     132     1246      77     1397      72    N      0
156088    2018     132     1335      68     1217      65    N      0

[156089 rows x 8 columns]

In [ ]:
#인덱스 자동 부여
print(df2.index)

RangeIndex(start=0, stop=156089, step=1)

5) CSV 파일 입력 및 %%writefile 명령

- 셸에 서술한 내용대로 텍스트 파일 만드는 명령

In [ ]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

In [ ]:
%%writefile C:/Users/user/Desktop/VSCode/sample2.csv
1, 1.11, one
2, 2.22, two
3, 3.33, three
에헤헿, 두번째, 파일

Overwriting C:/Users/user/Desktop/VSCode/sample2.csv

In [ ]:
pd.read_csv('sample1.csv')

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [ ]:
pd.read_csv('../sample2.csv')  #입력할 때 맨 윗줄에 column(c1, c2, c3)이 없으면 정보부터 나오나, 인덱스가 잘못 설정되어 있음을 알 수 있다.

     1   1.11     one
0    2   2.22     two
1    3   3.33   three
2  에헤헿    두번째      파일

- 그렇다면 어떻게 해야 할까? 데이터 파일에 열 인덱스 없는 경우 read_csv 명령의 names인수로 설정하기

In [ ]:
pd.read_csv('../sample2.csv', names = ['c1', 'c2', 'c3'])

    c1     c2      c3
0    1   1.11     one
1    2   2.22     two
2    3   3.33   three
3  에헤헿    두번째      파일

- 테이블 내의 특정 열을 행 인덱스로 지정하려면 index_col 인수 사용

In [ ]:
pd.read_csv('sample1.csv', index_col = 'c1')

      c2      c3
c1
1   1.11     one
2   2.22     two
3   3.33   three

In [ ]:
pd.read_csv('../sample2.csv', header = None)

     0      1       2
0    1   1.11     one
1    2   2.22     two
2    3   3.33   three
3  에헤헿    두번째      파일

- 자료 파일 중 건너뛰어야 할 행 있으면 skiprows 사용

In [ ]:
%%writefile sample4.txt
파일 제목: sample4.txt
데이터 포맷의 설명:
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample4.txt

In [ ]:
pd.read_csv('sample4.txt', skiprows = [0,1,4])  #해당하는 인덱스를 모두 안읽어오겠다는 의미.

   c1    c2      c3
0   1  1.11     one
1   3  3.33   three

- 특정 값을 NaN 취급하고 싶으면 na_values 인수에 NaN 값으로 취급할 값을 넣음

In [ ]:
%%writefile sample5.csv
c1, c2, c3
1, 1.11, one
2, , two
누락, 3.33, three

Writing sample5.csv

In [ ]:
dd = pd.read_csv('sample5.csv', na_values = ["누락"])
dd

    c1     c2      c3
0  1.0   1.11     one
1  2.0            two
2  NaN   3.33   three

In [ ]:
dd = pd.read_csv('sample5.csv', na_values = ["누락", " "])
dd

    c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

5-2) CSV 파일 출력

- 만든 데이터프레임을 CSV 파일로 변환하고싶으면  to_csv 사용

In [ ]:
dd.to_csv('sample6.csv')

In [ ]:
#!type 함수를 사용해 파일 내용을 확인O, 정확한 저장도 확인하기
!type sample6.csv

,c1, c2, c3
0,1.0,1.11, one
1,2.0,, two
2,,3.33, three

5-3) 인터넷 상의 CSV 파일 입력

- read_csv 명령 사용 시 파일 패스 대신 URL 지정 -> Pandas가 직접 해당 파일을 다운로드하여 읽음

In [ ]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
link = pd.read_csv(url)

In [ ]:
link.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
pd.set_option("display.max_rows", 20) # 앞뒤로 20행씩만 보여줌
link

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.concat([link.head(10), link.tail(10)])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

6. 데이터프레임 고급 인덱싱

- loc:

- df.loc[행 인덱싱 값, 열 인덱싱 값]

In [ ]:
arr = np.arange(10, 22)
print(arr)
print(arr.ndim)  #ndim(n-dimender) - 행렬 차원 수(리스트 형태는 1차원(선), 행렬 형태는 2차원(면),... 축 하나가 더해질수록 차원이 올라감)

[10 11 12 13 14 15 16 17 18 19 20 21]
1

In [ ]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

- 인덱싱 값을 하나만 받는 경우

In [ ]:
#loc 인덱서를 사용하며 인덱스를 하나만 넣으면 행(row)을 선택
df.loc["a"]

A    10
B    11
C    12
D    13
Name: a, dtype: int64

In [ ]:
#슬라이서도 사용O, 이때에는 loc를 쓰지 않는 경우와 같음
df.loc["b":"c"]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [ ]:
df["b":"c"]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [ ]:
df.A > 15

a    False
b    False
c     True
Name: A, dtype: bool

In [ ]:
df.loc[df.A > 15]

    A   B   C   D
c  18  19  20  21

In [ ]:
df2 = pd.DataFrame(np.arange(10, 26).reshape(4, 4),
                  # index=["a", "b", "c", "d"],
                  columns=["A", "B", "C", "D"])
df2

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21
d  22  23  24  25

In [ ]:
#슬라이스의 마지막 값 포함(index 없을 때)
df2.loc[1:2]

    A   B   C   D
1  14  15  16  17
2  18  19  20  21

In [ ]:
#슬라이스의 마지막 값 포함(index 있을 때)
df2.loc["b":"c"]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [ ]:
df2[1:2]

    A   B   C   D
b  14  15  16  17

- 인덱싱 값을 행과 열 모두 받는 경우

- ***df.loc[행 인덱스, 열 인덱스]와 같은 형태
- ***행 인덱스 라벨값이 a, 열 인덱스 라벨값이 A인 위치의 값을 구하기

In [ ]:
df.loc["a", "A"]  #a행 A열의 값

np.int64(10)

In [ ]:
df.loc["b":,"A"]  #b행부터 끝까지 A열의 값

b    14
c    18
Name: A, dtype: int64

In [ ]:
df.loc["a", :]  #a행의 모든 열 값

A    10
B    11
C    12
D    13
Name: a, dtype: int64

In [ ]:
df.loc[["a","b"],["B","D"]]  #a,b행 B,D열의 값

    B   D
a  11  13
b  15  17

In [ ]:
#A열에서 10보다 큰 행의 C, D  값을 보이시오.
#A열에서 10보다 큰 행을 먼저 선택
df.loc[df.A > 10]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [ ]:
df.loc[df.A > 10, ["C", "D"]]  #행이나 열 자리에 조건을 적어도 됨

    C   D
b  16  17
c  20  21

6-2) iloc 인덱서

- iloc 인덱서는 loc 인덱서와 반대로 라벨 아니라 순서를 나타내는 정수int 인덱스만 받음
- 라벨 이름 절대 X
- 오직 정수 순서(0,1,2,...)만 사용
- 튜플처럼 [행번호, 열번호] 형태

In [ ]:
df = pd.DataFrame(np.arange(10,22,1).reshape(3,4), index = ["a", "b", "c"], columns = ["A", "B", "C", "D"])
df

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [ ]:
df.iloc[0,1]

np.int64(11)

In [ ]:
df.iloc[:2, 2]

a    12
b    16
Name: C, dtype: int64

In [ ]:
df.iloc[0, -2:]

C    12
D    13
Name: a, dtype: int64

In [ ]:
df.iloc[2:3, 1:3]

    B   C
c  19  20

In [ ]:
# loc인덱서와 마찬가지로 인덱스 하나만 들어가면 행 선택
df.iloc[-1]

A    18
B    19
C    20
D    21
Name: c, dtype: int64

### 연습 문제 ###

In [ ]:
#1. 모든 행과 열에 라벨을 가지는 5,5 이상의 크기를 가지는 데이터프레임
df3 = pd.DataFrame(np.arange(1,26,1).reshape(5,5), index = ["1행", "2행", "3행", "4행", "5행"], columns = ["1열", "2열", "3열", "4열", "5열"])
df3
#2. 10가지 이상 방법으로 특정 행과 열 선택

    1열  2열  3열  4열  5열
1행   1   2   3   4   5
2행   6   7   8   9  10
3행  11  12  13  14  15
4행  16  17  18  19  20
5행  21  22  23  24  25

In [ ]:
df3.iloc[:-2]

    1열  2열  3열  4열  5열
1행   1   2   3   4   5
2행   6   7   8   9  10
3행  11  12  13  14  15

In [ ]:
df3.iloc[:-3]

    1열  2열  3열  4열  5열
1행   1   2   3   4   5
2행   6   7   8   9  10

In [ ]:
df3.loc["1":"4"]

    1열  2열  3열  4열  5열
1행   1   2   3   4   5
2행   6   7   8   9  10
3행  11  12  13  14  15

In [314]:
df3.iloc[:3]

    1열  2열  3열  4열  5열
1행   1   2   3   4   5
2행   6   7   8   9  10
3행  11  12  13  14  15

In [315]:
df3.iloc[1:3]

    1열  2열  3열  4열  5열
2행   6   7   8   9  10
3행  11  12  13  14  15

In [ ]:
df3.iloc[4]

1열    21
2열    22
3열    23
4열    24
5열    25
Name: 5행, dtype: int64

In [316]:
df3.loc["3행"]

1열    11
2열    12
3열    13
4열    14
5열    15
Name: 3행, dtype: int64

In [317]:
df3.loc["3행":"5행"]

    1열  2열  3열  4열  5열
3행  11  12  13  14  15
4행  16  17  18  19  20
5행  21  22  23  24  25

In [318]:
df3.loc["2행"].iloc[1]

np.int64(7)

In [320]:
df3.loc["1행"].iloc[3:]

4열    4
5열    5
Name: 1행, dtype: int64

7. 데이터프레임의 데이터 조작

7-1) 데이터 갯수 세기
- count 메서드 사용해 데이터 갯수 확인

In [ ]:
s = pd.Series(range(10))
s[3] = np.nan  #NaN 처리
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [323]:
#NaN 값은 count 하지 않음
s.count()

np.int64(9)

In [ ]:
np.random.seed(2)
#np.random.seed(2) : 난수를 예측 가능하도록 숫자 바꾸면 다른 배열 생성. 원하는 번호 아무거나 적어도 되는데, 그 다음부터는 '2'(예) 시드에서는 같은 랜덤숫자가 배정됨
df = pd.DataFrame(np.random.randint(5, size = (4, 4)), dtype = float)
#np.random.randint : 0에서 5사이의 정수를 가지는 4*4 배열 생성
df.iloc[2,3] = np.nan  #2행 3열의 값을 NaN 처리
df

     0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

- 데이터프레임에서는 각 열마다 별도로 데이터 갯수를 세기 때문에 누락된 부분 찾을 때 유용

In [325]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

In [ ]:
! pip install seaborn  #그래프 그릴 수 있는 모듈
import seaborn as sns
titanic = sns.load_dataset("titanic")  #데이터 불러오기
titanic.head()

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.3)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.60.1-cp313-cp313-win_amd64.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 8.1/8.1 MB 54.4 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 45.7 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 55.1 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.60.1 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5 seaborn-0.13.2

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
sns.get_dataset_names()  #데이터 분석을 위한 예제 데이터셋 이름들의 리스트를 출력

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

문제4

- 타이타닉 호 승객 데이터의 개수를 각 열마다 구하기

In [328]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [329]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

7-2) 카테고리 값 세기

- 시리즈의 값이 정수, 문자열, 카테고리 값인 경우 value_counts 메서드 이용해 각각의 값이 나온 횟수를 셀 수 있음

In [330]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size = 100))
s2.tail()

95    4
96    5
97    2
98    4
99    3
dtype: int32

In [331]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

- 데이터프레임에는 value_counts 사용할 때 각 열마다 별도로 적용해야 함

In [332]:
df

     0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [333]:
df[3].value_counts()

3
2.0    2
1.0    1
Name: count, dtype: int64

In [334]:
df[2].value_counts()

2
4.0    2
3.0    1
2.0    1
Name: count, dtype: int64

7-3) 정렬

- s2 시리즈의 각 데이터 값에 따른 데이터 갯수를 인덱스 따라 정렬

In [335]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [ ]:
s2.value_counts().sort_index()  #value_counts 한 것을 인덱스 정렬함(오름차순)

0    18
1    22
2    13
3    14
4    17
5    16
Name: count, dtype: int64

In [337]:
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [ ]:
#NaN 값이 있는 경우, 정렬 시 가장 마지막에 배치됨
s.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [ ]:
#큰 수에서 작은 수로 반대 방향 정렬하려면(내림차순) -> ascending = False
s.sort_values(ascending = False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64

In [ ]:
#by 인수로 정렬 기준이 되는 열 지정 -> by가 1이면 1열 기준으로 오름차순, 2면 2열 기준으로 오름차순
df.sort_values(by=1)

     0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [343]:
df.sort_values(by=3)

     0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
3  4.0  3.0  4.0  2.0
2  3.0  2.0  4.0  NaN

- by 인수에 리스트 값을 넣으면 이 순서대로 정렬 기준의 우선순위가 정해짐
- 리스트의 첫 번째 열을 기준으로 정렬한 후 동일한 값이 나오면 그 다음 열로 순서 따짐

In [342]:
df.sort_values(by=[1,2])

     0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

### 연습 문제 ###

sort_values() 이용해 타이타닉 호 승객에 대해 성별 인원수(sex), 나이별 인원수(age), 선실별 인원수(class), 사망/생존 인원수(alive)를 구하라.

In [ ]:
titanic.value_counts("sex").sort_index()
titanic.value_counts("age").sort_index()
titanic.value_counts("class").sort_index()
titanic.value_counts("alive").sort_index()

age
0.42     1
0.67     1
0.75     2
0.83     2
0.92     1
        ..
70.00    2
70.50    1
71.00    2
74.00    1
80.00    1
Name: count, Length: 88, dtype: int64

7-4) 행/열 합계

- 행과 열의 합계를 구할 때는 sum(axis) 메서드를 이용. axis 인수에는 합계로 인해 없어지는 방향축(0=행, 1=열)을 지정/ 행방향 합계를 구할 때는 sum(axis=1) 메서드 이용