0. 필요 패키지 다운로드 및 임포트

In [1]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 11.0/11.0 MB 67.9 MB/s  0:00:00
Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/12.8 MB 6.8 MB/s eta 0:00:02
   ---------------------------------------- 12.8/12.8 MB 35.3 MB/s  0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.3.5 pandas-2.3.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

1. 시리즈Series

- 1차원 배열의 값에 각 값에 대응되는 인덱스를 부여할 수 있는 구조
- 시리즈 = 값 + 인덱스

- 인덱스 길이 == 데이터 길이
- 인덱스 값은 문자열, 시간, 날짜, 정수 등도 모두 가능

- 리스트 = 파이썬 기본 자료구조  VS. 시리즈 = 판다스의 1차원 자료구조

In [8]:
#1-1) 시리즈 생성

s = pd.Series([9904312, 3448737, 2890451, 2466052], index = ["서울", "부산", "인천", "대구"])
s

#인덱스화하여 응용 가능 -> 따라서 겹치지 않아야 함

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [ ]:
#인덱스 지정하지 않으면 임의의 인덱스로 지정됨
s = pd.Series([9904312, 3448737, 2890451, 2466052])
s

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [9]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [10]:
s.values

array([9904312, 3448737, 2890451, 2466052])

In [11]:
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

- name 속성을 이용해 시리즈 데이터에 이름 붙임
- index.name 속성으로 시리즈의 인덱스에도 이름 붙임

In [12]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

1-2) 시리즈 연산

- 시리즈는 벡터화 연산 가능
- 연산이 시리즈 값에만 적용, 인덱스 값은 변하지 않음

In [13]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

In [ ]:
#리스트와 비교
lst = [1,2,3]
print("리스트연산\n")

1-3) 시리즈 인덱싱

In [17]:
#자료 순서 바꾸기
print(s[[0,3,1]])

print()

print(s[["서울", "대구", "부산"]])

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

C:\Users\user\AppData\Local\Temp\ipykernel_10488\2452755367.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0,3,1]])

In [18]:
s[(250e4 < s) & (s < 500e4)]  #인구가 250만 초과, 500만 미만인 경우

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 슬라이싱 가능
- 문자열일 경우, 콜론(:) 뒤에 오는 값도 결과에 포함

In [22]:
print(s[1:3])  #1번 인덱스부터 2번 인덱스까지(3 미포함)

print()

print(s["부산":"대구"])

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 라벨값이 영문 문자열인 경우 인덱스 라벨이 속성인 것처럼 점(.)을 이용해 해당 인덱스에 접근 가능

In [23]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [24]:
list(range(3))

[0, 1, 2]

In [28]:
s0.a

np.int64(0)

In [29]:
s0.c

np.int64(2)

1-4) 시리즈와 딕셔러니 자료형

- 시리즈 객체는 라벨 값에 의해 인덱싱이 가능, 실질적으로 인렉스 라벨 값을 키로 가지는 딕셔너리 자료형과 같다고 봄
- 딕셔너리 자료형에서 제공하는 in 연산, for 루프를 통한 각 원소릐 키와 값에 접근 가능

In [30]:
"서울" in s  #인덱스 라벨 중에 서울이 있는가?

True

In [31]:
"대전" in s  #인덱스 라벨 중에 대전이 있는가?

False

In [32]:
for k, v in s.items():
    print("%s = %d" % (k, v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052

In [35]:
#딕셔너리 객체에서 시리즈 만들기

s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 딕셔너리의 원소는 순서를 가지지 않으므로 시리즈의 데이털도 순서가 보장X
- 만약 순서를 정하고 싶다면 인덱스를 리스트로 지정해야 함

In [37]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}, index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [38]:
s2[1]

C:\Users\user\AppData\Local\Temp\ipykernel_10488\2825080482.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[1]

np.int64(9631482)

1-5) 인덱스 기반 연산

- 2015년도와 2010년도의

In [ ]:
#인덱스 같은 데이터에 대해서만 계산O
#***NaN(Not a Number, Not of Number)은 수치형 데이터가 없어서 계산된 결과가 없는 것, Null은 입력 아예 안된 것 (둘 다 혼용은 가능한데..... 좀 다르긴 함)***

ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [40]:
#null 값 아닌 것 찾기

ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [41]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [42]:
#증가율 계산

rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

1-6) 데이터의 갱신, 추가, 삭제

- 인덱싱을 이용하면 딕셔너리처럼 데이터를 갱신Update 하거나 추가Add 가능

In [43]:
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [ ]:
rs["대구"] = 1.41  #없던 것은 생기고, 있던 것은 새로 입력된 것으로 업데이트
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [45]:
#데이터 삭제

del rs["대구"]
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

### 연습 문제 ###

In [50]:
#1.
#(1) 임의로 두 개의 시리즈 객체를 만듦. 모두 문자열 인덱스를 가져야 하며, 두 시리즈에 공통적으로 포함되지 않는 라벨 있어야 함
#(2) 위에서 만든 두 시리즈 객체 이용해 사칙 연산

k1 = pd.Series({"백": 100, "이백": 200, "삼백": 300, "사백": 400}, index=["백", "이백", "삼백", "사백"])
k2 = pd.Series({"오백": 500, "육백": 600, "칠백": 700, "팔백": 800}, index=["오백", "육백", "칠백", "팔백"])

ressum = k1["백"] + k2["오백"]
resmin = k1["이백"] - k2["육백"]
resmul = k1["삼백"] * k2["칠백"]
resdiv = k1["사백"] / k2["팔백"]

print(ressum, resmin, resmul, resdiv)

600 -400 210000 0.5

In [53]:
cost = pd.Series([1500, 5000, 3500, 3000, 1000], index=["칫솔", "고무장갑", "포카칩", "베이킹소다", "스펀지"])
r = pd.Series([5, 1, 3, 2, 5], index=["칫솔", "고무장갑", "포카칩", "베이킹소다", "뒤집개"])

res = cost * r
res

고무장갑      5000.0
뒤집개          NaN
베이킹소다     6000.0
스펀지          NaN
칫솔        7500.0
포카칩      10500.0
dtype: float64

2) 데이터 프레임DataFrame

- 2차원 리스트를 매개변수로 전달하는 구조
- 2차원이므로 행방향 인덱스index와 열방향 인덱스Column가 존재
- 데이터프레임은 열까지 추가되어 열Columns, 인덱스index, 값Values으로 구성
- 시리즈는 인덱스와 값으로 구성

In [ ]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)  #인덱스에 index의 값들을, 열에 columns의 값을 지정해서 출력하겠다는 의미

print('데이터프레임 출력 :')
print('-'*18)
print(df)

데이터프레임 출력 :
------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

In [55]:
df1 = pd.DataFrame(values, columns = columns)
print(df1)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [57]:
print(df.index)
print(df.columns)
print(df.values)

Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3) 데이터프레임의 생성

-

In [60]:
# 리스트로 생성하기
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]

df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [61]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#열 지정

df = pd.DataFrame(data, columns = ['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [130]:
# 딕셔너리로 생성하기

data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]

df2 = pd.DataFrame(data)
df2

      2015     2010     2005     2000   지역  2010-2015 증가율
0  9904312  9631482  9762546  9853972  수도권         0.0283
1  3448737  3393191  3512547  3655437  경상권         0.0163
2  2890451  2632035  2517680  2466338  수도권         0.0982
3  2466052  2431774  2456016  2473990  경상권         0.0141

In [131]:
df2 = pd.DataFrame(data, index = index, columns = columns)
print(df2)

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [132]:
print(df2.index)  #현재 타입 = Object, 수정 불가한 상태. 수정하려면 타입을 바꾸고 수정해야 함
print(df2.columns)
print(df2.values)

Index(['서울', '부산', '인천', '대구'], dtype='object')
Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')
[['수도권' 9904312 9631482 9762546 9853972 0.0283]
 ['경상권' 3448737 3393191 3512547 3655437 0.0163]
 ['수도권' 2890451 2632035 2517680 2466338 0.0982]
 ['경상권' 2466052 2431774 2456016 2473990 0.0141]]

In [133]:
#전치행렬 가능
df2.T

                    서울       부산       인천       대구
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [134]:
df2  #df2 자체는 변하지 않음. 전치한 결과만 출력하는 게 .T

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

3-2) 열 데이터의 갱신, 추가, 삭제

- 데이터프레임은 열 시리즈의 딕셔너리로 볼 수 있으므로 열 단위로 데이터를 갱신, 추가, 삭제 가능

In [135]:
#"2010-2015 증가율" 이라는 이름의 열 추가

df2["2010~2015 증가율"] = df2["2010-2015 증가율"] * 100
df2

     지역     2015     2010     2005     2000  2010-2015 증가율  2010~2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283           2.83
부산  경상권  3448737  3393191  3512547  3655437         0.0163           1.63
인천  수도권  2890451  2632035  2517680  2466338         0.0982           9.82
대구  경상권  2466052  2431774  2456016  2473990         0.0141           1.41

In [136]:
# "2005-2010 증가율"이라는 이름의 열 추가
df2["2005-2010 증가율"] = ((df2["2010"] - df2["2005"]) / df2["2005"] * 100).round(3)
df2

,지역,2015,2010,2005,2000,2010-2015 증가율,2010~2015 증가율,2005-2010 증가율
서울,수도권,9904312,9631482,9762546,9853972,0.0283,2.83,-1.343
부산,경상권,3448737,3393191,3512547,3655437,0.0163,1.63,-3.398
인천,수도권,2890451,2632035,2517680,2466338,0.0982,9.82,4.542
대구,경상권,2466052,2431774,2456016,2473990,0.0141,1.41,-0.987

In [137]:
#"2010~2015 증가율"이라는 이름의 열 삭제
del df2["2010~2015 증가율"]
df2

     지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283         -1.343
부산  경상권  3448737  3393191  3512547  3655437         0.0163         -3.398
인천  수도권  2890451  2632035  2517680  2466338         0.0982          4.542
대구  경상권  2466052  2431774  2456016  2473990         0.0141         -0.987

In [138]:
#하나의 열만 인덱싱하면 시리즈 반환
df2["지역"]

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [139]:
type(df2["지역"])

pandas.core.series.Series

In [140]:
#여러 개의 열을 인덱싱하면 부분적인 데이터프레임이 반환
df2[["2010", "2015"]]

       2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [141]:
type(df2[["2010", "2015"]])

pandas.core.frame.DataFrame

In [142]:
#2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
df2[["2010"]]

       2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [143]:
type(df2[["2010"]])

pandas.core.frame.DataFrame

In [144]:
#문자열 라벨을 가지는 경우 정수 인덱스를 열 인덱싱에 사용X
df2[0]

KeyError: 0

In [145]:
#열 인덱스가 정수형일 때 인덱스 값에 정수 사용O
df3 = pd.DataFrame(np.arange(12).reshape(3,4))
df3

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
(0,12,1)

In [146]:
df3[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [147]:
df3[[1,2]]

   1   2
0  1   2
1  5   6
2  9  10

3-4) 행 인덱싱

- 행 단위로 인덱싱 하고자 하면 항상 슬라이싱Slicing 사용
- 인덱스 값이 문자 라벨이면 라벨 슬라이싱 O